### ISSUE TITLE
ImportError: cannot import name 'ensure_converter' from 'sssom.context'

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#130]
Another build error, after merging #129:
```
14:11:11  + python3.9 run.py transform
14:11:16  /var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic.error_wrappers:ValidationError` has been moved to `pydantic:ValidationError`.
14:11:16    warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
14:11:18  Traceback (most recent call last):
14:11:18    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/run.py", line 9, in <module>
14:11:18      from kg_phenio.normalize import normalize
14:11:18    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/normalize.py", line 2, in <module>
14:11:18      from universalizer.norm import clean_and_normalize_graph
14:11:18    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/universalizer/norm.py", line 15, in <module>
14:11:18      from universalizer.oak_utils import get_cats_from_oak
14:11:18    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/universalizer/oak_utils.py", line 11, in <module>
14:11:18      from oaklib.constants import OAKLIB_MODULE
14:11:18    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/oaklib/__init__.py", line 7, in <module>
14:11:18      from oaklib.interfaces import BasicOntologyInterface  # noqa:F401
14:11:18    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/oaklib/interfaces/__init__.py", line 8, in <module>
14:11:18      from oaklib.interfaces.text_annotator_interface import TextAnnotatorInterface
14:11:18    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/oaklib/interfaces/text_annotator_interface.py", line 22, in <module>
14:11:18      from oaklib.utilities.lexical.lexical_indexer import create_or_load_lexical_index
14:11:18    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/oaklib/utilities/lexical/lexical_indexer.py", line 21, in <module>
14:11:18      from sssom.context import ensure_converter
14:11:18  ImportError: cannot import name 'ensure_converter' from 'sssom.context' (/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/sssom/context.py)
```

**Comment by caufieldjh** [comment]
Wait, this is the same as #126, so I'll just reopen that
