### ISSUE TITLE
`KeyError: 'val'` breaks transform

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#159]
In the current build:
```python
Checking for errors...
11:05:01  Found error at line 10103: <rdfs:comment></rdfs:comment>.
11:05:01  Found error at line 10157: <rdfs:comment></rdfs:comment>.
11:05:01  Found error at line 8293848: <oboInOwl:hasDbXref></oboInOwl:hasDbXref>.
11:05:01  Found error at line 8294035: <oboInOwl:hasDbXref></oboInOwl:hasDbXref>.
11:05:01  Found error at line 21571358: <rdfs:comment></rdfs:comment>.
11:05:01  Found error at line 23906990: <oboInOwl:hasExactSynonym></oboInOwl:hasExactSynonym>.
11:05:01  Converting data/raw/phenio.owl to data/raw/phenio.json...
11:05:01  Complete.
11:05:01  Transforming to KGX TSV with config in transform.yaml...
11:05:01  [KGX][cli_utils.py][           transform] INFO: Spawning process for 'phenio-transform'
11:06:09  multiprocessing.pool.RemoteTraceback: 
11:06:09  """
11:06:09  Traceback (most recent call last):
11:06:09    File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
11:06:09      result = (True, func(*args, **kwds))
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/cli/cli_utils.py", line 871, in transform_source
11:06:09      transformer.transform(input_args, output_args)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/transformer.py", line 241, in transform
11:06:09      self.process(source_generator, intermediate_sink)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/transformer.py", line 337, in process
11:06:09      for rec in source:
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 62, in parse
11:06:09      yield from chain(n, e)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 86, in read_nodes
11:06:09      yield self.read_node(n)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 109, in read_node
11:06:09      node_properties = self.parse_meta(node["id"], node["meta"])
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 336, in parse_meta
11:06:09      synonyms = [s["val"] for s in meta["synonyms"]]
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 336, in <listcomp>
11:06:09      synonyms = [s["val"] for s in meta["synonyms"]]
11:06:09  KeyError: 'val'
11:06:09  """
11:06:09  
11:06:09  The above exception was the direct cause of the following exception:
11:06:09  
11:06:09  Traceback (most recent call last):
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/run.py", line 100, in <module>
11:06:09      cli()
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
11:06:09      return self.main(*args, **kwargs)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
11:06:09      rv = self.invoke(ctx)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
11:06:09      return _process_result(sub_ctx.command.invoke(sub_ctx))
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
11:06:09      return ctx.invoke(self.callback, **ctx.params)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
11:06:09      return __callback(*args, **kwargs)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/run.py", line 75, in transform
11:06:09      kg_transform(*args, **kwargs)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform.py", line 36, in transform
11:06:09      t.run()
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform_utils/phenio/phenio_transform.py", line 73, in run
11:06:09      self.parse(k, data_file, k)
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform_utils/phenio/phenio_transform.py", line 158, in parse
11:06:09      transform(
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/cli/cli_utils.py", line 521, in transform
11:06:09      graphs = [r.get() for r in results]
11:06:09    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/cli/cli_utils.py", line 521, in <listcomp>
11:06:09      graphs = [r.get() for r in results]
11:06:09    File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
11:06:09      raise self._value
11:06:09  KeyError: 'val'
```

Likely due to the error described by @matentzn here: https://github.com/biolink/kgx/pull/502

**Comment by caufieldjh** [comment]
Workaround for now is to use phenio.json from the ontology build (https://github.com/monarch-initiative/phenio/releases/download/v2024-11-25/phenio.json) though this may miss potential structure errors impacting transform to KGX TSV (it doesn't do it this time, on my local build)

**Comment by matentzn** [comment]
Not sure this wull solve the problem.. But the next phenio build will!

OBA has been fixed: https://github.com/obophenotype/bio-attribute-ontology/releases/tag/v2024-11-26
