### ISSUE TITLE
Jenkins build fails when trying to download `robot`

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#67]
The Jenkins build fails during the `pip install` as follows:
```
10:57:03  + ./venv/bin/pip install .
10:57:05  Processing /var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo
10:57:11      ERROR: Command errored out with exit status 1:
10:57:11       command: /var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-l94dsogz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-l94dsogz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-l94dsogz/pip-egg-info
10:57:11           cwd: /tmp/pip-req-build-l94dsogz/
10:57:11      Complete output (41 lines):
10:57:11      running egg_info
10:57:11      creating /tmp/pip-req-build-l94dsogz/pip-egg-info/kg_phenio.egg-info
10:57:11      writing /tmp/pip-req-build-l94dsogz/pip-egg-info/kg_phenio.egg-info/PKG-INFO
10:57:11      writing dependency_links to /tmp/pip-req-build-l94dsogz/pip-egg-info/kg_phenio.egg-info/dependency_links.txt
10:57:11      writing requirements to /tmp/pip-req-build-l94dsogz/pip-egg-info/kg_phenio.egg-info/requires.txt
10:57:11      writing top-level names to /tmp/pip-req-build-l94dsogz/pip-egg-info/kg_phenio.egg-info/top_level.txt
10:57:11      writing manifest file '/tmp/pip-req-build-l94dsogz/pip-egg-info/kg_phenio.egg-info/SOURCES.txt'
10:57:11      reading manifest file '/tmp/pip-req-build-l94dsogz/pip-egg-info/kg_phenio.egg-info/SOURCES.txt'
10:57:11      writing manifest file '/tmp/pip-req-build-l94dsogz/pip-egg-info/kg_phenio.egg-info/SOURCES.txt'
10:57:11      Traceback (most recent call last):
10:57:11        File "<string>", line 1, in <module>
10:57:11        File "/tmp/pip-req-build-l94dsogz/setup.py", line 83, in <module>
10:57:11          robot_setup()
10:57:11        File "/tmp/pip-req-build-l94dsogz/post_setup/post_setup.py", line 21, in robot_setup
10:57:11          urllib.request.urlretrieve(remotefile, localfile)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
10:57:11          with contextlib.closing(urlopen(url, data)) as fp:
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
10:57:11          return opener.open(url, data, timeout)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 531, in open
10:57:11          response = meth(req, response)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
10:57:11          response = self.parent.error(
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 563, in error
10:57:11          result = self._call_chain(*args)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
10:57:11          result = func(*args)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
10:57:11          return self.parent.open(new, timeout=req.timeout)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 531, in open
10:57:11          response = meth(req, response)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
10:57:11          response = self.parent.error(
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 569, in error
10:57:11          return self._call_chain(*args)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
10:57:11          result = func(*args)
10:57:11        File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
10:57:11          raise HTTPError(req.full_url, code, msg, hdrs, fp)
10:57:11      urllib.error.HTTPError: HTTP Error 503: Egress is over the account limit.
10:57:11      Did not find robot.jar. Downloading from https://github.com/ontodev/robot/releases/download/v1.9.0/robot.jar...
10:57:11      ----------------------------------------
10:57:11  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The error `urllib.error.HTTPError: HTTP Error 503: Egress is over the account limit.` appears to refer to downloading either the `robot.jar` or `robot` run script, from the following URLs, respectively:

https://github.com/ontodev/robot/releases/download/v1.9.0/robot.jar

https://raw.githubusercontent.com/ontodev/robot/master/bin/robot

Both resolve as expected through browser.

**Comment by caufieldjh** [comment]
Could not reproduce. Next build downloaded `robot` with no issues.

Guess it's a transient thing.
