### ISSUE TITLE
Transform fails due to `KeyError: 'val'` with "synonyms"

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#73]
Transform from phenio.json to phenio nodes and edges doesn't get too far before it encounters a KeyError:
```
15:06:47  + python3.8 run.py transform
15:10:38  WARNING:rdflib.term:https://w3id.org/biolink/vocab/Dicty Phenotypes does not look like a valid URI, trying to serialize this will break.
15:10:38  WARNING:rdflib.term:https://w3id.org/biolink/vocab/Dicty Phenotypes does not look like a valid URI, trying to serialize this will break.
15:10:38  WARNING:rdflib.term:https://w3id.org/biolink/vocab/Dicty Phenotypes does not look like a valid URI, trying to serialize this will break.
15:10:38  WARNING:rdflib.term:https://w3id.org/biolink/vocab/Dicty Phenotypes does not look like a valid URI, trying to serialize this will break.
15:10:38  WARNING:rdflib.term:https://w3id.org/biolink/vocab/Dicty Phenotypes does not look like a valid URI, trying to serialize this will break.
15:10:38  WARNING:rdflib.term:https://w3id.org/biolink/vocab/Dicty Phenotypes does not look like a valid URI, trying to serialize this will break.
15:12:29  Setting up ROBOT...
15:12:29  Did not find robot.jar. Downloading from https://github.com/ontodev/robot/releases/download/v1.9.0/robot.jar...
15:12:29  Did not find robot. Downloading from https://raw.githubusercontent.com/ontodev/robot/master/bin/robot...
15:12:29  ROBOT path: /var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/robot
15:12:29  ROBOT evironment variables: -Xmx12g -XX:+UseG1GC
15:12:29  Found ontology at data/raw/phenio.owl
15:12:29  Converting data/raw/phenio.owl to data/raw/phenio.json...
15:12:29  Complete.
15:12:29  Traceback (most recent call last):
15:12:29    File "run.py", line 85, in <module>
15:12:29      cli()
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
15:12:29      return self.main(*args, **kwargs)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
15:12:29      rv = self.invoke(ctx)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
15:12:29      return _process_result(sub_ctx.command.invoke(sub_ctx))
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
15:12:29      return ctx.invoke(self.callback, **ctx.params)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
15:12:29      return __callback(*args, **kwargs)
15:12:29    File "run.py", line 62, in transform
15:12:29      kg_transform(*args, **kwargs)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform.py", line 37, in transform
15:12:29      t.run()
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform_utils/phenio/phenio_transform.py", line 50, in run
15:12:29      self.parse(k, data_file, k)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform_utils/phenio/phenio_transform.py", line 80, in parse
15:12:29      transform(inputs=[data_file_json],
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/cli/cli_utils.py", line 560, in transform
15:12:29      transform_source(
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/cli/cli_utils.py", line 869, in transform_source
15:12:29      transformer.transform(input_args, output_args)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/transformer.py", line 229, in transform
15:12:29      self.process(source_generator, sink)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/transformer.py", line 332, in process
15:12:29      for rec in source:
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 62, in parse
15:12:29      yield from chain(n, e)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 86, in read_nodes
15:12:29      yield self.read_node(n)
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 106, in read_node
15:12:29      node_properties = self.parse_meta(node["id"], node["meta"])
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 319, in parse_meta
15:12:29      synonyms = [s["val"] for s in meta["synonyms"]]
15:12:29    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.8/site-packages/kgx/source/obograph_source.py", line 319, in <listcomp>
15:12:29      synonyms = [s["val"] for s in meta["synonyms"]]
15:12:29  KeyError: 'val'
```

Looks like the input fails to parse, specifically due to a list of synonyms without any values.

**Comment by caufieldjh** [comment]
> a list of synonyms without any values.

or, a list of synonyms with one or more predicates but no "val" for one of those predicates.

**Comment by caufieldjh** [comment]
This issue is with some of the synonyms in `PLANA` and `WBPhenotype`. `WBPhenotype` is coming in from uPheno base-plus (the http://purl.obolibrary.org/obo/WBPhenotype_ is explicitly defined as a base IRI) but I'm not sure about `PLANA`.
The impacted IRIs are:
```
http://purl.obolibrary.org/obo/PLANA_0000001
http://purl.obolibrary.org/obo/PLANA_0000003
http://purl.obolibrary.org/obo/PLANA_0000004
http://purl.obolibrary.org/obo/PLANA_0000005
http://purl.obolibrary.org/obo/PLANA_0000006
http://purl.obolibrary.org/obo/PLANA_0000007
http://purl.obolibrary.org/obo/PLANA_0000011
http://purl.obolibrary.org/obo/PLANA_0000015
http://purl.obolibrary.org/obo/PLANA_0000018
http://purl.obolibrary.org/obo/PLANA_0000019
http://purl.obolibrary.org/obo/PLANA_0000021
http://purl.obolibrary.org/obo/PLANA_0000022
http://purl.obolibrary.org/obo/PLANA_0000029
http://purl.obolibrary.org/obo/PLANA_0000030
http://purl.obolibrary.org/obo/PLANA_0000032
http://purl.obolibrary.org/obo/PLANA_0000038
http://purl.obolibrary.org/obo/PLANA_0000041
http://purl.obolibrary.org/obo/PLANA_0000042
http://purl.obolibrary.org/obo/PLANA_0000053
http://purl.obolibrary.org/obo/PLANA_0000056
http://purl.obolibrary.org/obo/PLANA_0000058
http://purl.obolibrary.org/obo/PLANA_0000059
http://purl.obolibrary.org/obo/PLANA_0000060
http://purl.obolibrary.org/obo/PLANA_0000063
http://purl.obolibrary.org/obo/PLANA_0000064
http://purl.obolibrary.org/obo/PLANA_0000065
http://purl.obolibrary.org/obo/PLANA_0000067
http://purl.obolibrary.org/obo/PLANA_0000068
http://purl.obolibrary.org/obo/PLANA_0000076
http://purl.obolibrary.org/obo/PLANA_0000080
http://purl.obolibrary.org/obo/PLANA_0000085
http://purl.obolibrary.org/obo/PLANA_0000087
http://purl.obolibrary.org/obo/PLANA_0000089
http://purl.obolibrary.org/obo/PLANA_0000098
http://purl.obolibrary.org/obo/PLANA_0000104
http://purl.obolibrary.org/obo/PLANA_0000105
http://purl.obolibrary.org/obo/PLANA_0000110
http://purl.obolibrary.org/obo/PLANA_0000113
http://purl.obolibrary.org/obo/PLANA_0000114
http://purl.obolibrary.org/obo/PLANA_0000116
http://purl.obolibrary.org/obo/PLANA_0000117
http://purl.obolibrary.org/obo/PLANA_0000118
http://purl.obolibrary.org/obo/PLANA_0000119
http://purl.obolibrary.org/obo/PLANA_0000121
http://purl.obolibrary.org/obo/PLANA_0000122
http://purl.obolibrary.org/obo/PLANA_0000123
http://purl.obolibrary.org/obo/PLANA_0000124
http://purl.obolibrary.org/obo/PLANA_0000125
http://purl.obolibrary.org/obo/PLANA_0000126
http://purl.obolibrary.org/obo/PLANA_0000127
http://purl.obolibrary.org/obo/PLANA_0000128
http://purl.obolibrary.org/obo/PLANA_0000130
http://purl.obolibrary.org/obo/PLANA_0000131
http://purl.obolibrary.org/obo/PLANA_0000134
http://purl.obolibrary.org/obo/PLANA_0000135
http://purl.obolibrary.org/obo/PLANA_0000138
http://purl.obolibrary.org/obo/PLANA_0000140
http://purl.obolibrary.org/obo/PLANA_0000141
http://purl.obolibrary.org/obo/PLANA_0000142
http://purl.obolibrary.org/obo/PLANA_0000143
http://purl.obolibrary.org/obo/PLANA_0000201
http://purl.obolibrary.org/obo/PLANA_0000211
http://purl.obolibrary.org/obo/PLANA_0000214
http://purl.obolibrary.org/obo/PLANA_0000215
http://purl.obolibrary.org/obo/PLANA_0000217
http://purl.obolibrary.org/obo/PLANA_0000218
http://purl.obolibrary.org/obo/PLANA_0000222
http://purl.obolibrary.org/obo/PLANA_0000227
http://purl.obolibrary.org/obo/PLANA_0000228
http://purl.obolibrary.org/obo/PLANA_0000229
http://purl.obolibrary.org/obo/PLANA_0000230
http://purl.obolibrary.org/obo/PLANA_0000234
http://purl.obolibrary.org/obo/PLANA_0000237
http://purl.obolibrary.org/obo/PLANA_0000239
http://purl.obolibrary.org/obo/PLANA_0000409
http://purl.obolibrary.org/obo/PLANA_0000410
http://purl.obolibrary.org/obo/PLANA_0000417
http://purl.obolibrary.org/obo/PLANA_0000418
http://purl.obolibrary.org/obo/PLANA_0000421
http://purl.obolibrary.org/obo/PLANA_0000422
http://purl.obolibrary.org/obo/PLANA_0000423
http://purl.obolibrary.org/obo/PLANA_0000427
http://purl.obolibrary.org/obo/PLANA_0000430
http://purl.obolibrary.org/obo/PLANA_0000431
http://purl.obolibrary.org/obo/PLANA_0000462
http://purl.obolibrary.org/obo/PLANA_0000466
http://purl.obolibrary.org/obo/PLANA_0000467
http://purl.obolibrary.org/obo/PLANA_0000468
http://purl.obolibrary.org/obo/PLANA_0000482
http://purl.obolibrary.org/obo/PLANA_0000483
http://purl.obolibrary.org/obo/PLANA_0000484
http://purl.obolibrary.org/obo/PLANA_0000494
http://purl.obolibrary.org/obo/PLANA_0000499
http://purl.obolibrary.org/obo/PLANA_0000501
http://purl.obolibrary.org/obo/PLANA_0000502
http://purl.obolibrary.org/obo/PLANA_0000504
http://purl.obolibrary.org/obo/PLANA_0000505
http://purl.obolibrary.org/obo/PLANA_0000506
http://purl.obolibrary.org/obo/PLANA_0000507
http://purl.obolibrary.org/obo/PLANA_0000508
http://purl.obolibrary.org/obo/PLANA_0000509
http://purl.obolibrary.org/obo/PLANA_0000510
http://purl.obolibrary.org/obo/PLANA_0000513
http://purl.obolibrary.org/obo/PLANA_0000514
http://purl.obolibrary.org/obo/PLANA_0000515
http://purl.obolibrary.org/obo/PLANA_0000518
http://purl.obolibrary.org/obo/PLANA_0000519
http://purl.obolibrary.org/obo/PLANA_0000520
http://purl.obolibrary.org/obo/PLANA_0000521
http://purl.obolibrary.org/obo/PLANA_0000522
http://purl.obolibrary.org/obo/PLANA_0000523
http://purl.obolibrary.org/obo/PLANA_0000524
http://purl.obolibrary.org/obo/PLANA_0000525
http://purl.obolibrary.org/obo/PLANA_0000526
http://purl.obolibrary.org/obo/PLANA_0000527
http://purl.obolibrary.org/obo/PLANA_0000528
http://purl.obolibrary.org/obo/PLANA_0000529
http://purl.obolibrary.org/obo/PLANA_0000530
http://purl.obolibrary.org/obo/PLANA_0000531
http://purl.obolibrary.org/obo/PLANA_0000532
http://purl.obolibrary.org/obo/PLANA_0000533
http://purl.obolibrary.org/obo/PLANA_0000534
http://purl.obolibrary.org/obo/PLANA_0000535
http://purl.obolibrary.org/obo/PLANA_0000536
http://purl.obolibrary.org/obo/PLANA_0000537
http://purl.obolibrary.org/obo/PLANA_0000539
http://purl.obolibrary.org/obo/PLANA_0000540
http://purl.obolibrary.org/obo/PLANA_0000543
http://purl.obolibrary.org/obo/PLANA_0000547
http://purl.obolibrary.org/obo/PLANA_0000550
http://purl.obolibrary.org/obo/PLANA_0000552
http://purl.obolibrary.org/obo/PLANA_0000558
http://purl.obolibrary.org/obo/PLANA_0000561
http://purl.obolibrary.org/obo/PLANA_0000562
http://purl.obolibrary.org/obo/PLANA_0000565
http://purl.obolibrary.org/obo/PLANA_0000566
http://purl.obolibrary.org/obo/PLANA_0002000
http://purl.obolibrary.org/obo/PLANA_0002001
http://purl.obolibrary.org/obo/PLANA_0002003
http://purl.obolibrary.org/obo/PLANA_0002006
http://purl.obolibrary.org/obo/PLANA_0002007
http://purl.obolibrary.org/obo/PLANA_0002009
http://purl.obolibrary.org/obo/PLANA_0002010
http://purl.obolibrary.org/obo/PLANA_0002014
http://purl.obolibrary.org/obo/PLANA_0002017
http://purl.obolibrary.org/obo/PLANA_0002021
http://purl.obolibrary.org/obo/PLANA_0002022
http://purl.obolibrary.org/obo/PLANA_0002023
http://purl.obolibrary.org/obo/PLANA_0002024
http://purl.obolibrary.org/obo/PLANA_0002025
http://purl.obolibrary.org/obo/PLANA_0002026
http://purl.obolibrary.org/obo/PLANA_0002029
http://purl.obolibrary.org/obo/PLANA_0002030
http://purl.obolibrary.org/obo/PLANA_0002031
http://purl.obolibrary.org/obo/PLANA_0002032
http://purl.obolibrary.org/obo/PLANA_0002033
http://purl.obolibrary.org/obo/PLANA_0002034
http://purl.obolibrary.org/obo/PLANA_0002036
http://purl.obolibrary.org/obo/PLANA_0002038
http://purl.obolibrary.org/obo/PLANA_0002039
http://purl.obolibrary.org/obo/PLANA_0002040
http://purl.obolibrary.org/obo/PLANA_0002041
http://purl.obolibrary.org/obo/PLANA_0002045
http://purl.obolibrary.org/obo/PLANA_0002046
http://purl.obolibrary.org/obo/PLANA_0002048
http://purl.obolibrary.org/obo/PLANA_0002049
http://purl.obolibrary.org/obo/PLANA_0002050
http://purl.obolibrary.org/obo/PLANA_0002052
http://purl.obolibrary.org/obo/PLANA_0002053
http://purl.obolibrary.org/obo/PLANA_0002054
http://purl.obolibrary.org/obo/PLANA_0002056
http://purl.obolibrary.org/obo/PLANA_0002057
http://purl.obolibrary.org/obo/PLANA_0002058
http://purl.obolibrary.org/obo/PLANA_0002059
http://purl.obolibrary.org/obo/PLANA_0002060
http://purl.obolibrary.org/obo/PLANA_0002063
http://purl.obolibrary.org/obo/PLANA_0002064
http://purl.obolibrary.org/obo/PLANA_0002066
http://purl.obolibrary.org/obo/PLANA_0002068
http://purl.obolibrary.org/obo/PLANA_0002070
http://purl.obolibrary.org/obo/PLANA_0002074
http://purl.obolibrary.org/obo/PLANA_0002076
http://purl.obolibrary.org/obo/PLANA_0002077
http://purl.obolibrary.org/obo/PLANA_0002079
http://purl.obolibrary.org/obo/PLANA_0002080
http://purl.obolibrary.org/obo/PLANA_0002082
http://purl.obolibrary.org/obo/PLANA_0002088
http://purl.obolibrary.org/obo/PLANA_0002089
http://purl.obolibrary.org/obo/PLANA_0002090
http://purl.obolibrary.org/obo/PLANA_0002091
http://purl.obolibrary.org/obo/PLANA_0002092
http://purl.obolibrary.org/obo/PLANA_0002094
http://purl.obolibrary.org/obo/PLANA_0002095
http://purl.obolibrary.org/obo/PLANA_0002097
http://purl.obolibrary.org/obo/PLANA_0002098
http://purl.obolibrary.org/obo/PLANA_0002099
http://purl.obolibrary.org/obo/PLANA_0002101
http://purl.obolibrary.org/obo/PLANA_0002102
http://purl.obolibrary.org/obo/PLANA_0002103
http://purl.obolibrary.org/obo/PLANA_0002104
http://purl.obolibrary.org/obo/PLANA_0002105
http://purl.obolibrary.org/obo/PLANA_0002106
http://purl.obolibrary.org/obo/PLANA_0002107
http://purl.obolibrary.org/obo/PLANA_0002110
http://purl.obolibrary.org/obo/PLANA_0002111
http://purl.obolibrary.org/obo/PLANA_0002116
http://purl.obolibrary.org/obo/PLANA_0002118
http://purl.obolibrary.org/obo/PLANA_0002119
http://purl.obolibrary.org/obo/PLANA_0002120
http://purl.obolibrary.org/obo/PLANA_0002121
http://purl.obolibrary.org/obo/PLANA_0002125
http://purl.obolibrary.org/obo/PLANA_0002126
http://purl.obolibrary.org/obo/PLANA_0002129
http://purl.obolibrary.org/obo/PLANA_0002130
http://purl.obolibrary.org/obo/PLANA_0002131
http://purl.obolibrary.org/obo/PLANA_0002132
http://purl.obolibrary.org/obo/PLANA_0002133
http://purl.obolibrary.org/obo/PLANA_0002135
http://purl.obolibrary.org/obo/PLANA_0002136
http://purl.obolibrary.org/obo/PLANA_0002137
http://purl.obolibrary.org/obo/PLANA_0002138
http://purl.obolibrary.org/obo/PLANA_0002139
http://purl.obolibrary.org/obo/PLANA_0002140
http://purl.obolibrary.org/obo/PLANA_0002141
http://purl.obolibrary.org/obo/PLANA_0003000
http://purl.obolibrary.org/obo/PLANA_0003100
http://purl.obolibrary.org/obo/PLANA_0003106
http://purl.obolibrary.org/obo/PLANA_0003109
http://purl.obolibrary.org/obo/PLANA_0003115
http://purl.obolibrary.org/obo/PLANA_0003116
http://purl.obolibrary.org/obo/PLANA_0003200
http://purl.obolibrary.org/obo/PLANA_0003201
http://purl.obolibrary.org/obo/PLANA_0003202
http://purl.obolibrary.org/obo/PLANA_0003203
http://purl.obolibrary.org/obo/PLANA_0003205
http://purl.obolibrary.org/obo/PLANA_0003206
http://purl.obolibrary.org/obo/PLANA_0003207
http://purl.obolibrary.org/obo/PLANA_0003208
http://purl.obolibrary.org/obo/PLANA_0003209
http://purl.obolibrary.org/obo/PLANA_0003210
http://purl.obolibrary.org/obo/PLANA_0003211
http://purl.obolibrary.org/obo/PLANA_0003212
http://purl.obolibrary.org/obo/PLANA_0003213
http://purl.obolibrary.org/obo/PLANA_0003214
http://purl.obolibrary.org/obo/PLANA_0003215
http://purl.obolibrary.org/obo/PLANA_0003216
http://purl.obolibrary.org/obo/PLANA_0003217
http://purl.obolibrary.org/obo/PLANA_0003218
http://purl.obolibrary.org/obo/PLANA_0003219
http://purl.obolibrary.org/obo/PLANA_0003220
http://purl.obolibrary.org/obo/PLANA_0003221
http://purl.obolibrary.org/obo/PLANA_0003222
http://purl.obolibrary.org/obo/PLANA_0003223
http://purl.obolibrary.org/obo/PLANA_0003224
http://purl.obolibrary.org/obo/PLANA_0003225
http://purl.obolibrary.org/obo/PLANA_0003226
http://purl.obolibrary.org/obo/PLANA_0003227
http://purl.obolibrary.org/obo/PLANA_0003228
http://purl.obolibrary.org/obo/PLANA_0003229
http://purl.obolibrary.org/obo/PLANA_0003230
http://purl.obolibrary.org/obo/PLANA_0003231
http://purl.obolibrary.org/obo/PLANA_0003232
http://purl.obolibrary.org/obo/PLANA_0003233
http://purl.obolibrary.org/obo/PLANA_0003234
http://purl.obolibrary.org/obo/PLANA_0003235
http://purl.obolibrary.org/obo/PLANA_0003236
http://purl.obolibrary.org/obo/PLANA_0003237
http://purl.obolibrary.org/obo/PLANA_0003238
http://purl.obolibrary.org/obo/PLANA_0003239
http://purl.obolibrary.org/obo/PLANA_0003240
http://purl.obolibrary.org/obo/PLANA_0003241
http://purl.obolibrary.org/obo/PLANA_0003242
http://purl.obolibrary.org/obo/PLANA_0003243
http://purl.obolibrary.org/obo/PLANA_0003244
http://purl.obolibrary.org/obo/PLANA_0003245
http://purl.obolibrary.org/obo/PLANA_0003246
http://purl.obolibrary.org/obo/PLANA_0003247
http://purl.obolibrary.org/obo/PLANA_0003248
http://purl.obolibrary.org/obo/PLANA_0003249
http://purl.obolibrary.org/obo/PLANA_0003250
http://purl.obolibrary.org/obo/PLANA_0003251
http://purl.obolibrary.org/obo/PLANA_0003252
http://purl.obolibrary.org/obo/PLANA_0003253
http://purl.obolibrary.org/obo/PLANA_0003254
http://purl.obolibrary.org/obo/PLANA_0003255
http://purl.obolibrary.org/obo/PLANA_0003256
http://purl.obolibrary.org/obo/PLANA_0003257
http://purl.obolibrary.org/obo/PLANA_0003258
http://purl.obolibrary.org/obo/PLANA_0003302
http://purl.obolibrary.org/obo/PLANA_0003304
http://purl.obolibrary.org/obo/PLANA_0003305
http://purl.obolibrary.org/obo/PLANA_0003400
http://purl.obolibrary.org/obo/PLANA_0003401
http://purl.obolibrary.org/obo/PLANA_0003402
http://purl.obolibrary.org/obo/PLANA_0003501
http://purl.obolibrary.org/obo/PLANA_0003503
http://purl.obolibrary.org/obo/PLANA_0003603
http://purl.obolibrary.org/obo/PLANA_0003605
http://purl.obolibrary.org/obo/PLANA_0003606
http://purl.obolibrary.org/obo/PLANA_0003608
http://purl.obolibrary.org/obo/PLANA_0003609
http://purl.obolibrary.org/obo/PLANA_0003610
http://purl.obolibrary.org/obo/PLANA_0003700
http://purl.obolibrary.org/obo/PLANA_0003701
http://purl.obolibrary.org/obo/PLANA_0003702
http://purl.obolibrary.org/obo/PLANA_0003703
http://purl.obolibrary.org/obo/PLANA_0003704
http://purl.obolibrary.org/obo/PLANA_0003705
http://purl.obolibrary.org/obo/PLANA_0003706
http://purl.obolibrary.org/obo/PLANA_0003707
http://purl.obolibrary.org/obo/PLANA_0003708
http://purl.obolibrary.org/obo/PLANA_0003709
http://purl.obolibrary.org/obo/PLANA_0003710
http://purl.obolibrary.org/obo/PLANA_0003711
http://purl.obolibrary.org/obo/PLANA_0003712
http://purl.obolibrary.org/obo/PLANA_0003713
http://purl.obolibrary.org/obo/PLANA_0003714
http://purl.obolibrary.org/obo/PLANA_0003715
http://purl.obolibrary.org/obo/PLANA_0003716
http://purl.obolibrary.org/obo/PLANA_0003717
http://purl.obolibrary.org/obo/PLANA_0003718
http://purl.obolibrary.org/obo/PLANA_0003719
http://purl.obolibrary.org/obo/PLANA_0003720
http://purl.obolibrary.org/obo/PLANA_0003721
http://purl.obolibrary.org/obo/PLANA_0003722
http://purl.obolibrary.org/obo/PLANA_0003723
http://purl.obolibrary.org/obo/PLANA_0003724
http://purl.obolibrary.org/obo/PLANA_0003725
http://purl.obolibrary.org/obo/PLANA_0003726
http://purl.obolibrary.org/obo/PLANA_0003727
http://purl.obolibrary.org/obo/PLANA_0003728
http://purl.obolibrary.org/obo/PLANA_0003729
http://purl.obolibrary.org/obo/PLANA_0003730
http://purl.obolibrary.org/obo/PLANA_0003731
http://purl.obolibrary.org/obo/PLANA_0003732
http://purl.obolibrary.org/obo/PLANA_0003733
http://purl.obolibrary.org/obo/PLANA_0003734
http://purl.obolibrary.org/obo/PLANA_0003735
http://purl.obolibrary.org/obo/PLANA_0003736
http://purl.obolibrary.org/obo/PLANA_0003737
http://purl.obolibrary.org/obo/PLANA_0003738
http://purl.obolibrary.org/obo/PLANA_0003739
http://purl.obolibrary.org/obo/PLANA_0003740
http://purl.obolibrary.org/obo/PLANA_0003741
http://purl.obolibrary.org/obo/PLANA_0003742
http://purl.obolibrary.org/obo/PLANA_0003743
http://purl.obolibrary.org/obo/PLANA_0004504
http://purl.obolibrary.org/obo/PLANA_0004511
http://purl.obolibrary.org/obo/PLANA_0004512
http://purl.obolibrary.org/obo/PLANA_0004513
http://purl.obolibrary.org/obo/PLANA_0004514
http://purl.obolibrary.org/obo/PLANA_0004516
http://purl.obolibrary.org/obo/PLANA_0004517
http://purl.obolibrary.org/obo/PLANA_0004518
http://purl.obolibrary.org/obo/PLANA_0004519
http://purl.obolibrary.org/obo/PLANA_0004521
http://purl.obolibrary.org/obo/PLANA_0004527
http://purl.obolibrary.org/obo/PLANA_0004529
http://purl.obolibrary.org/obo/PLANA_0004530
http://purl.obolibrary.org/obo/PLANA_0004531
http://purl.obolibrary.org/obo/PLANA_0004532
http://purl.obolibrary.org/obo/PLANA_0004533
http://purl.obolibrary.org/obo/PLANA_0004534
http://purl.obolibrary.org/obo/PLANA_0007503
http://purl.obolibrary.org/obo/PLANA_0007511
http://purl.obolibrary.org/obo/PLANA_0007513
http://purl.obolibrary.org/obo/PLANA_0007514
http://purl.obolibrary.org/obo/PLANA_0007515
http://purl.obolibrary.org/obo/PLANA_0007516
http://purl.obolibrary.org/obo/PLANA_0007518
http://purl.obolibrary.org/obo/PLANA_0007539
http://purl.obolibrary.org/obo/PLANA_0007540
http://purl.obolibrary.org/obo/PLANA_0007541
http://purl.obolibrary.org/obo/PLANA_0007546
http://purl.obolibrary.org/obo/PLANA_0007547
http://purl.obolibrary.org/obo/PLANA_0007548
http://purl.obolibrary.org/obo/PLANA_0007550
http://purl.obolibrary.org/obo/PLANA_0007551
http://purl.obolibrary.org/obo/PLANA_0007553
http://purl.obolibrary.org/obo/PLANA_0007555
http://purl.obolibrary.org/obo/PLANA_0007556
http://purl.obolibrary.org/obo/PLANA_0007557
http://purl.obolibrary.org/obo/PLANA_0007558
http://purl.obolibrary.org/obo/PLANA_0007559
http://purl.obolibrary.org/obo/WBPhenotype_0001117
http://purl.obolibrary.org/obo/WBPhenotype_0001660
http://purl.obolibrary.org/obo/WBPhenotype_0001661
```

**Comment by caufieldjh** [comment]
Anyway, these IRIs all contain at least one synonym with a predicate missing a value. These predicated may be either `hasExactSynonym`, `hasNarrowSynonym`, or `hasRelatedSynonym`.

**Comment by caufieldjh** [comment]
These are present in the owl, too (example):
```
    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/WBPhenotype_0001117">
        <obo:IAO_0000115>Cell-cell contacts are abnormal in the early embryo.</obo:IAO_0000115>
        <oboInOwl:hasOBONamespace>C_elegans_phenotype_ontology</oboInOwl:hasOBONamespace>
        <oboInOwl:hasNarrowSynonym></oboInOwl:hasNarrowSynonym>
        <oboInOwl:hasBroadSynonym>Emb</oboInOwl:hasBroadSynonym>
        <oboInOwl:id>WBPhenotype:0001117</oboInOwl:id>
        <rdfs:label>cell cell contacts abnormal early emb (WBP)</rdfs:label>
```

**Comment by matentzn** [comment]
Can you make a phenio issue assign to me I will push this upstream

**Comment by caufieldjh** [comment]
Righto - see https://github.com/monarch-initiative/phenio/issues/20
