### ISSUE TITLE
Build error: 'EnumDefinition' object has no attribute 'range'

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#93]
Most recent build encounters this `AttributeError` at what looks like the conclusion of the merge step:
```
14:17:33  [KGX][cli_utils.py][               merge] INFO: Spawning process for 'phenio-merged'
14:17:33  [KGX][cli_utils.py][        parse_source] INFO: Processing source 'phenio-merged'
14:19:54  [KGX][cli_utils.py][               merge] INFO: Merged graph has 275527 nodes and 1638357 edges
14:20:12  [KGX][cli_utils.py][               merge] INFO: Writing merged graph to merged-kg-tsv
14:23:49  [KGX][cli_utils.py][               merge] INFO: Writing merged graph to merged-kg-nt
14:25:25  Traceback (most recent call last):
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/run.py", line 98, in <module>
14:25:25      cli()
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
14:25:25      return self.main(*args, **kwargs)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
14:25:25      rv = self.invoke(ctx)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
14:25:25      return _process_result(sub_ctx.command.invoke(sub_ctx))
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
14:25:25      return ctx.invoke(self.callback, **ctx.params)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
14:25:25      return __callback(*args, **kwargs)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/run.py", line 93, in merge
14:25:25      load_and_merge(yaml, processes)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/merge_utils/merge_kg.py", line 35, in load_and_merge
14:25:25      merged_graph = merge(yaml_file, processes=processes)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/cli/cli_utils.py", line 728, in merge
14:25:25      transformer.transform(input_args, output_args)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/transformer.py", line 281, in transform
14:25:25      sink = self.get_sink(**output_args)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/transformer.py", line 436, in get_sink
14:25:25      return s(self, **kwargs)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/sink/rdf_sink.py", line 75, in __init__
14:25:25      self.property_types = get_biolink_property_types()
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/utils/kgx_utils.py", line 487, in get_biolink_property_types
14:25:25      property_type = get_type_for_property(p)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/utils/kgx_utils.py", line 529, in get_type_for_property
14:25:25      t = get_type_for_property(r)
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/utils/kgx_utils.py", line 522, in get_type_for_property
14:25:25      r = e.range
14:25:25    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/jsonasobj2/_jsonobj.py", line 160, in __getattr__
14:25:25      return super().__getattribute__(item)
14:25:25  AttributeError: 'EnumDefinition' object has no attribute 'range'
```

Seems to be something related to Biolink types, but not sure why this isn't raised until writing to nt (through kgx's rdf sink).

**Comment by caufieldjh** [comment]
Workaround here is to disable producing nt for now
