### ISSUE TITLE
Build error due to 404 error with LinkML schemaview

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#96]
In the most recent KG build on Jenkins, this happens:
```
14:03:56  Transforming to KGX TSV...
14:03:56  Traceback (most recent call last):
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/run.py", line 98, in <module>
14:03:56      cli()
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
14:03:56      return self.main(*args, **kwargs)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
14:03:56      rv = self.invoke(ctx)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
14:03:56      return _process_result(sub_ctx.command.invoke(sub_ctx))
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
14:03:56      return ctx.invoke(self.callback, **ctx.params)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
14:03:56      return __callback(*args, **kwargs)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/run.py", line 73, in transform
14:03:56      kg_transform(*args, **kwargs)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform.py", line 35, in transform
14:03:56      t.run()
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform_utils/phenio/phenio_transform.py", line 56, in run
14:03:56      self.parse(k, data_file, k)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/kg_phenio/transform_utils/phenio/phenio_transform.py", line 123, in parse
14:03:56      transform(
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/cli/cli_utils.py", line 560, in transform
14:03:56      transform_source(
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/cli/cli_utils.py", line 869, in transform_source
14:03:56      transformer.transform(input_args, output_args)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/transformer.py", line 229, in transform
14:03:56      self.process(source_generator, sink)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/transformer.py", line 332, in process
14:03:56      for rec in source:
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 62, in parse
14:03:56      yield from chain(n, e)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 86, in read_nodes
14:03:56      yield self.read_node(n)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 124, in read_node
14:03:56      category = self.get_category(curie, node)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/kgx/source/obograph_source.py", line 246, in get_category
14:03:56      element = self.toolkit.get_element(category)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/bmt/toolkit.py", line 585, in get_element
14:03:56      element = self.view.get_element(parsed_name)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 874, in get_element
14:03:56      e = self.get_class(element, imports=imports)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 486, in get_class
14:03:56      c = self.all_classes(imports=imports).get(class_name, None)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 290, in all_classes
14:03:56      classes = copy(self._get_dict(CLASSES, imports))
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 416, in _get_dict
14:03:56      schemas = self.all_schema(imports)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 235, in all_schema
14:03:56      return [m[sn] for sn in self.imports_closure(imports)]
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 211, in imports_closure
14:03:56      imported_schema = self.load_import(sn)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 185, in load_import
14:03:56      schema = load_schema_wrap(sname + '.yaml',
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 70, in load_schema_wrap
14:03:56      schema = yaml_loader.load(path, target_class=SchemaDefinition, **kwargs)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
14:03:56      results = self.load_any(*args, **kwargs)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/loaders/yaml_loader.py", line 32, in load_any
14:03:56      return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/loaders/loader_root.py", line 58, in load_source
14:03:56      data = hbread(source, metadata, metadata.base_path, accept_header)
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/hbreader/__init__.py", line 260, in hbread
14:03:56      with hbopen(source, open_info, base_path, accept_header, is_actual_data, read_codec) as f:
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/hbreader/__init__.py", line 188, in hbopen
14:03:56      raise e
14:03:56    File "/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/hbreader/__init__.py", line 184, in hbopen
14:03:56      response = urlopen(req, context=ssl._create_unverified_context())
14:03:56    File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
14:03:56      return opener.open(url, data, timeout)
14:03:56    File "/usr/lib/python3.9/urllib/request.py", line 523, in open
14:03:56      response = meth(req, response)
14:03:56    File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
14:03:56      response = self.parent.error(
14:03:56    File "/usr/lib/python3.9/urllib/request.py", line 561, in error
14:03:56      return self._call_chain(*args)
14:03:56    File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
14:03:56      result = func(*args)
14:03:56    File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
14:03:56      raise HTTPError(req.full_url, code, msg, hdrs, fp)
14:03:56  urllib.error.HTTPError: HTTP Error 404: https://raw.githubusercontent.com/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types.yaml
```

The schemaview utility is attempting to retrieve `types.yaml` from the local linkml_runtime package, but 404's.

**Comment by caufieldjh** [comment]
The schema yamls are still in the `linkml_runtime` repo at least: https://github.com/linkml/linkml-runtime/tree/main/linkml_runtime/linkml_model/model/schema

So are they in the installed package?

**Comment by caufieldjh** [comment]
Though that URL is also pretty strange:
`https://raw.githubusercontent.com/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types.yaml`

**Comment by caufieldjh** [comment]
Could also be due to Jenkins weirdness, e.g., if schemaview is attempting to use a local context to assemble that URL (like it's just inserting the working directory to `https://raw.githubusercontent.com/ {path} /venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types.yaml`, but in this case the working directory is already `/var/lib/jenkins/workspace/ledge-graph-hub_kg-phenio_master/gitrepo/`

**Comment by caufieldjh** [comment]
Should be fixed by https://github.com/linkml/linkml-runtime/pull/253 - closing
